### ISSUE TITLE
JCS can't transform bare JSON `null`

### ISSUE THREAD

**Issue by moskyb** [gowebpki/jcs#2]
## Minimal reproduction

```Go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/gowebpki/jcs"
)

func main() {
	var something *string
	err := json.Unmarshal([]byte("null"), &something)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		// => nothing, never fires
	}

	fmt.Printf("Something: %v\n", something)
	// => Something: <nil>, so go JSON can definitely parse this

	_, err = jcs.Transform([]byte("null"))
	fmt.Println(err)
	// => Unexpected EOF reached
}
```

## Issue

It appears that when a bare null is passed into JCS (ie just the string `null`, with no quotes or braces of any kind, the JCS parser emits an `Unexpected EOF reached` error

**Comment by jordan2175** [comment]
A fix has been proposed as a pull request to address this. Can you verify that it solves your problem? If so, I accept the pull request and merge it into the main branch.

**Comment by cyberphone** [comment]
Since the pull request contains test files for simple values, I think you can safely commit the changes.

**Comment by jordan2175** [comment]
Pull request has been merged. This should fix the problem. Please let us know if there are other issues.

**Comment by moskyb** [comment]
could you make a release so that we can include the fix in our project?

**Comment by jordan2175** [comment]
Version 1.0.1 has been released. This contains the fix for JSON NULL values.
